name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: * * * * *

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
    - name: 准备完成
      uses: actions/checkout@v2

    - name: 下载架构编译配置文件
      run: |

        mkdir -p ./rk35xx
        wget -O ./rk35xx/feeds.conf https://fw0.koolcenter.com/iStoreOS/h88k/feeds.conf
        wget -O ./rk35xx/.config https://fw0.koolcenter.com/iStoreOS/h88k/config.buildinfo
        echo 'CONFIG_TARGET_DEVICE_rockchip_rk35xx_DEVICE_panther_x2=y'>> ./rk35xx/.config
       
    - name: 同步配置
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"

    - name: 删除运行记录
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.ACCESS_TOKEN }}
